### ISSUE TITLE
BigInteger.gcd() returns the incorrect value

### ISSUE THREAD

**Issue by zukky162** [natade-jp/konpeito#5]
`BigInteger.gcd()` function returns the incorrect value in specific arguments.
For example, I expect `konpeito.BigInteger.create(33919).gcd(1500)` to return `1`, but actually `9`.

Also, konpeito.Fraction makes unexpected numerator and denominator by normalization with incorrect gcd value.
https://github.com/natade-jp/konpeito/blob/v6.0.0/src/math/core/Fraction.js#L278

I think there is a problem with limiting the number of loops in gcd function.
https://github.com/natade-jp/konpeito/blob/v6.0.0/src/math/core/BigInteger.js#L1913

**Comment by natade-jp** [comment]
Thank you for your report.
I would like to confirm the contents.

**Comment by natade-jp** [comment]
Thank you for your report.
As pointed out by zukky162, there was a case where a composite number consisting of many prime factors could not be calculated correctly.
This has been fixed in Ver. 6.0.1.
